package fake

import "math/rand"

func One() string {
	return fakeHeadlines[rand.Intn(len(fakeHeadlines))]
}

var fakeHeadlines = []string{
	`Mark Addis, former Tasmanian premier Sir Angus Bethune dies`,
	`KraMar pulls dog food Christmas gift`,
	`Cricket bosses caught out for blood`,
	`AMA WA President Dr David Eddey, chair of the North Shore Eruv proposal`,
	`Woman's body found after bush disappearance`,
	`Brisbane-bound... Michael Ennis and fans alike.`,
	`Studies show increase in Perth's night of fatal car smash`,
	`A large tree sits on a carnival float shocks in popular picnic area`,
	`Appeal launched to stop Broulee New Year's Eve patrols at campsites`,
	`Grave fears held for Waterfall victims`,
	`The Footscray Trugo club has also attacked the Flannery article.`,
	`Police hunt escapees after Perth car smash`,
	`The founder and former Liberal Party in WA to Indonesia to cut violence against women`,
	`Dr Kim Smith wants to be caught: victim's mum`,
	`NT minister rejects calls for permanent night crew`,
	`To dob or not nearly enough?`,
	`CLP demands release of Marlon Noble`,
	`Researchers track travels of rare disease outbreak`,
	`Domestic dispute ends in Victoria`,
	`Five rescued after boat blast`,
	`Urban experience used in ram raids on pharmacies`,
	`Brendan Fevola... on his Sunday morning jog.`,
	`Baby meerkat stolen from home`,
	`Football legend Diego Maradona plays with some Australian flags`,
	`Govt under fire from Carters Road`,
	`Accountant jailed for drug offences after Perth car crash mum walks 1km for help as storms approach`,
	`Artist stands with seven men after being bullied.`,
	`Celebrity hairdresser jailed for ramming police car rescues Four German tourists rescued on Canning Stock Route`,
	`It has been committed to stand trial on 4 June, 2009.`,
	`Steven James Newton in talks to his body, with Dr Robyn Grote.`,
	`Peel superintendent claims Old Coast Road one of the Ngarrindjeri Aboriginal people seek refugee status`,
	`Jake and his wife Debra as he exits NSW politics`,
	`GrainCorp accused of trying to save woman`,
	`Grain carrier detained after immigration raid`,
	`Man shot dead in Dukes Highway accident site`,
	`Australian actress Cate Blanchett speaks onstage at the Hunter`,
	`Women take on flood claims: RACQ`,
	`Miowera - the main park of NSW declared disaster areas`,
	`Court refuses New Farm Park to lose Tas captaincy`,
	`At least 600 ill from typhoid fever outbreak threatens cyclone victims face rising costs`,
	`Indonesian fisherman Justinus Lahama holds up team-mate Johnathan Thurston after winning the corella battle`,
	`London bombing looks to airports for cost cutting`,
	`Wagga police bust in Brisbane`,
	`Coalition calls for petrol price watch`,
	`Broken but out of jail`,
	`Puddy's sister rejects drug trafficker's plea for driver death`,
	`Brogan admits to sex with 13 year old Dexter Williams.`,
	`DFAT says 15 killed in south west car crash near Geelong`,
	`Port Arthur memorial service for dentist to service Tenterfield continues`,
	`New centre to benefit pastoralists`,
	`Push for more suppliers`,
	`Wayne Bradshaw on the anti-siphoning list`,
	`Appeal for killer of family law`,
	`Photographer Martin Schreiber looks at as his resident duck family as they make their way to Dungog`,
	`Nixon denies misleading Royal Commission into child protection minister Malarndirri McCarthy`,
	`Byrock Public School in shock after Australian jailed in Bulgaria`,
	`Accused getaway driver granted extraordinary licence`,
	`Man jailed for 30 years of anti-terror laws - 9/11 Remembered - Ten Years On`,
	`Lianna Brown, who lay in the Lord Howe airport reopens`,
	`Vioxx compo battle could go to water over treatment of disabled man`,
	`10cm leech pulled from dental health scheme`,
	`Man charged after border blitz`,
	`Murder accused teen refused bail over video game-related stabbing`,
	`Hospitals get new principal`,
	`Hotel hold-up interrupted by diesel spill in Brisbane`,
	`Gossip Girl star Blake Lively goes Green`,
	`Qld Water Police site in northern India`,
	`A wind turbine layout to go off air in a class of their featured acts`,
	`Police Commissioner's son to death`,
	`Water bomber could have been taken out in force to police shooting`,
	`Search for missing Victorian teen`,
	`Hot air balloon floats in Port Kembla`,
	`Sunshine Coast boat builder in foreground and Fort Dennison.`,
	`Teenager killed in truck crash causes airport chaos`,
	`Police believe Sally Winter murdered her husband Stephen Uttley on their side of a sign at a service station robberies`,
	`Worst bushfires in Grampians`,
	`Ngoombujarra won three Australian Film Institute awards for Blackfellas, Black and white still photo of the Bringing Them Home report, which documented the impact`,
	`Hitchhiker's mother angry at the house in Downer two years off for rough play`,
	`Aussie honeymooner killed in Warwick farming accident`,
	`Don Burke says planners need to protect Old Bar beach`,
	`ACT court reserves decision in Clough murder trial begins`,
	`International child health conference begins in Gippsland road crashes`,
	`Radiation therapist shortage frustrating parents`,
	`Police hunt for tick-resistance genes`,
	`Supporters concerned over nursing home`,
	`Feral felines eradicated from Qld to face trial over Nambour body`,
	`Surfing alpaca hits the fan`,
	`Grain pours from a cliff at Walker Flat.`,
	`Trouble in the Todd River drops`,
	`Reward offered to help move obese patients`,
	`The home-made kit plan, the Bushby Mustang, had taken a dog near the wreck of HMAS Stuart`,
	`Newspapers losing out to dry towns`,
	`Farmers want relaxed rules for WA tourism regions`,
	`Porn industry takes classification board to probe motorway noise complaints`,
	`Darwin bombing death toll in Bangladesh storms`,
	`Racism, hypocrisy, whatever. Can't you take a hit in Japan`,
	`Strong community the answer to climate change science`,
	`Brothel squeezes into Wagga woman's death was preventable`,
	`Rogers has copped his suspension on the Hume Highway between Craigieburn and Wallan.`,
	`Man admits to internet sex sting`,
	`Wooden pipe find excites bird-watchers`,
	`Council backs Govt's plan to share knowledge`,
	`Baiada set to worsen`,
	`Heroin addict jailed over car cannabis`,
	`DPP angry city shooting charges dropped against former principal upheld`,
	`Man charged over McGurk shooting`,
	`Abbott makes play for Glory`,
	`ABC Radio News journalists Murray Cornish, Siobhan Barry and Penny Timms, interviews a woman whose car was rammed at Teralba.`,
	`Powerline inspection failures out in Yuendumu following the expulsion of Mich`,
	`Vaccines may have been killed by her mother`,
	`Bombers pay the price of gold`,
	`Brad Pitt and Transport Minister Gerry McCarthy will face court over robberies`,
	`Police say the woman has full support: ambassador`,
	`Funeral to farewell outback`,
	`Plea for disabled Australians`,
	`A meteorologist looks at Rotto's grim prison past`,
	`Govt sticks by Daly land clearing going on year after chemicals were found in house fire`,
	`Jim Bacon dies aged 55`,
	`Illegal fishing captures fall in the 2003 movie, Ned Kelly.`,
	`Archbishop criticises euthanasia in Easter road toll low in northern New South Wales.`,
	`The publisher of the Black Swan sweeps Spirit awards`,
	`Hunting temporarily halted in Hunter Valley chemical plant fire`,
	`In form ... Bulldogs half-back Brent Sherwin looks to avoid a public nuisance powers begin in WA chickens`,
	`Mandatory jail terms cut`,
	`Four face court over alleged toddler torture`,
	`Anthony Mundine loses his cool with match referee`,
	`Jorge Lorenzo returns to haunt Howard.`,
	`Man charged at bedside hearing over attempted fraud`,
	`Man charged over double murder at Mayfield`,
	`Ten Canoes, 20 VBs: actor fined for speeding in a cell in the Goldfields sets off locals`,
	`Surfers look at the Australian War Memorial.`,
	`Emergency crews issue warning after 4 hours in rubble`,
	`Hungry Hobos was one of five as catamaran sinks`,
	`Man to face with Carlton's Shaun Hampson at the age of painting coming to Australia`,
	`Cyclone Ellie cover the Bruce Highway flood fix`,
	`Without balance that paywall will not be eaten.`,
	`Son was warned not to boost water supply pipeline`,
	`Experts warn against water trading`,
	`Riverland ripe for picking`,
	`Hayden falls after being locked out in straight sets.`,
	`Bruno, aka Sacha Baron Cohen, famous for his camera work`,
	`Tumour breakthrough could save death row`,
	`London authority to probe mine creek worries`,
	`ABC helicopter crash kills Alexandria Patriarch, Australian`,
	`Police tend to a bed with infants`,
	`Mindarie mineral sands mine permit`,
	`Sydney Swans player Barry Hall announces retirement`,
	`Try-scorer Nathan Cayless is congratulated during his high school bomb threats`,
	`Barrick Gold's communications manager, Bill Shallvey, speaks with Private James Smith - Rifleman, Alpha Company`,
	`Indigenous stars gather for Hobart Anzac Day win`,
	`Brick company fined for insulation death`,
	`The rise of cloud over festival`,
	`Police investigate fatal Halloween accident`,
	`Fan charged over fatal Longford road crash`,
	`Bureaucrats blamed for rise in young people think they are still in critical condition`,
	`Carr's would-be assassin freed`,
	`More than a nickel`,
	`NSW considering car confiscations for speeding in a scene from the Planetarium in Brisbane`,
	`Chinese workers say they will be better protected now the Australian flag hoisted on the huge rock face of Johann Sebastian Bach`,
	`Robinvale policeman assaulted in road crash that killed unborn baby`,
	`Residents have win in Perth on February 25, 2011.`,
	`Last male WWI veteran Smout farewelled in Melbourne house attack`,
	`Train derails after hitting him with a child's legs.`,
	`Barrick Gold's communications manager, Bill Shallvey, speaks with ABC Launceston News reporter James Kelly and his wife Rachel looks on`,
	`Drug accused couple to front court over indecent assault`,
	`Man to face gun charges`,
	`Multi-car crash brings road toll reaches eight`,
	`Police lay drugs charges after cannabis seized in Sydney's south-west`,
	`Melbourne MFB firefighter Louise Cannon talks about putting snow in the crash.`,
	`Japan is the cult of personality: a reflection on the shark attack`,
	`Libs promise $225 million gas pipeline back on rate cut`,
	`$250k contract put on YouTube`,
	`Police investigate Perth market fire`,
	`Threat charges against Hobart company`,
	`Couple charged over Donnybrook death`,
	`Kava seized at casino`,
	`Fire crews believe the motorist drove past other cars waiting by the law overturned.`,
	`Police investigate man's death after forced eviction`,
	`Soldiers clean up Karumba water`,
	`Witnesses sought to discuss Ponting's bat`,
	`Bligh takes reins in Queensland flood clean-up continues`,
	`Inquest told mother couldn't have poisoned Tasmanian devils`,
	`Ethiopia lifts ban on uranium exports to shamed abattoirs suspended`,
	`Prime Minister Julia Gillard and Howard applaud Bin Laden warns US, Iraqi Shiites`,
	`Trial over man shot dead during a concrete power pole`,
	`Wheat crops devastated by flash flooding`,
	`Helicopter hovers above Gulf`,
	`Scientists search for missing Australian in Saudi Arabia watches Ali Hussein Rehema of Iraq perform an overhead kick`,
	`A modest asylum seeker fears for own life`,
	`Early hummingbird fossil found in fatal crash`,
	`Trees uprooted by Cyclone Yasi on February 3, 2011.`,
	`Australian diver Matthew Mitcham says the ACT Magistrates Court in Sydney`,
	`Transportable homes for young`,
	`Water tower inquest hears about Bundaberg hospital's procedures`,
	`Ten shares soar as farmers regenerate land`,
	`Intimate body piercing banned for 12 weeks`,
	`Inquiry highlights flaws in the Melbourne Magistrates Court.`,
	`Margaret River calls for counter-terrorism boycott`,
	`Police investigate cause of Duigan plane crash`,
	`Protest over native vegetation clearing`,
	`Waratahs and Australia work together on water rations`,
	`Man pleads guilty for prostituting 16yo daughter`,
	`Byrne's boss, June Dally Watkins, on the run after schoolgirl assault`,
	`Russia to host Olympic trials`,
	`Man jailed over 3yo son's death`,
	`New Life for Indigenous kids in Brisbane unit fire`,
	`New paediatrician starts at James Price Point`,
	`Boy charged over Moe murders`,
	`Woman jailed for murder accused granted bail due to pressures on their side of the six white boomers, raised by farmer Michael James in Bridgenorth, Tasmania`,
	`Dr Kelly Thambimuthu says there seems to give police more clout`,
	`Turnbull: why I will vote for baby found in Antarctica`,
	`Gondola passengers ferried through snow on the rise`,
	`Work recommences at Holden plant`,
	`Moses parts the red carpet`,
	`Calls for second helping of Junior MasterChef cooks competition in Qld's south-east`,
	`Woman critically hurt after car hits Melb restaurant`,
	`Matthew Johnson gets life for silent movie`,
	`Robin Waring, who died after being hit by car wheel`,
	`Man charged with perverting course of action`,
	`Man jailed over violent Mullewa brawl`,
	`Podiatrists robbed by Sydney thieves`,
	`Lilydale man bailed over airport death`,
	`MPs set to play preliminary final`,
	`US President George W Bush where US troops in 1989.`,
	`Highway bridge damaged by blazes`,
	`Disability service provider attack`,
	`Close friends Don Lane farewelled`,
	`Police seek witnesses after car ploughs into Sydney house`,
	`Improve Aboriginal camps in South-East Asia, 1979.`,
	`No bail for woman in court over Gold Coast`,
	`Proud and poignant: we've found the World Cup`,
	`The ship Seahorse Spirit of Tasmania in crisis season`,
	`Senior Constable Stuart Pontil talks about the conviction of Norm Marlborou`,
	`Catholic Health lobbies for water authority`,
	`Mt Morgan mine dam clean up Christmas Island`,
	`Historic World War I white feather found in Box Hill apartment`,
	`35 Queenslanders awarded bravery medal for Bali drugs case`,
	`Study considers benefits of Telstra sale`,
	`Government approves $12b Inpex gas project gets greenlight`,
	`A music institution closes its doors on September 29, 2009.`,
	`AU troops begin assault on woman in house fire claims two lives in 10 years since Port Arthur anniversary`,
	`Teen gets tougher on illegal fireworks`,
	`Glandular fever link to Koroit fires`,
	`Swine flu blamed for permanent security guard wanted by Interpol`,
	`A debilitating illness from a Henry Lawson short story about an asbestos scare in Australian politics`,
	`Smoke billows from the Mortlock Islands. Tapuanu represent ancestral spirit beings and were worn by the dancer Vaslav Nijinsky in Le Dieu Bleu.`,
	`Creating a bright future for Eden port`,
	`Hundreds of babies at risk of a car in place for rivers and streams between Cooktown and Cardwell.`,
	`Australia slides down list of farms owned by the massive wall of water.`,
	`WA Govt dump Minister over breathalyser incident`,
	`Osama bin Laden praise`,
	`Race courses ordered to pay, perform community service`,
	`Portland aluminium smelter to sign up`,
	`Folau to join SA wilderness protection zone is set to buy doughnuts`,
	`Empire Of The Opera`,
	`Drunk driver sentenced for crime victims: Rann`,
	`Stomach bug hits Army cadets suffer food poisoning`,
	`Researchers develop treatment for hypertension`,
	`Authorities make major drug network suspects plead not guilty of assault charges`,
	`Zoning anomaly for Young Australian award`,
	`Man dies after hitting roo`,
	`Donald Trump speaks at the 2012 Olympics.`,
	`Police culture change needed to establish alcohol advisory body`,
	`Scientists discover new Aboriginal art exploration dies`,
	`Mining company ready to demolish mine-damaged homes`,
	`Smoking hurts knees, study finds invaders first farmed Europe`,
	`Concerns raised over e-passport`,
	`Shane Watson bowls during a paddle out in outback`,
	`Police get details of users`,
	`A cattle ship refloated`,
	`Powerful Rangers move closer to foreign private bankers`,
	`Rediscovered Goya drawings to go ahead despite threats`,
	`A teenage girl is still time to make a meal at Karkan on the return of mouse plague respite`,
	`Technicians look at books on a wintery morning`,
	`Greg Zipf, a Queensland Police have praised two missionaries who helped a pregnant woman`,
	`Cambodia seeks arrest of opposition leader flees to Peru`,
	`Raids trigger drug supply face court over hospital shooting`,
	`Recovering Stosur blows into Adelaide`,
	`Insulation firm pleads guilty over hurt passenger`,
	`LtoR Michelle Luangkhoth and Madeleine Lacey arrive at the Port of Brisbane`,
	`Graeme Connors accepts the best film at AACTA Awards`,
	`Pearl producers fail to heed police warnings on trial over fatal 35-car crash`,
	`Australian resident jailed for 25 years.`,
	`Ai Weiwei poses with husband`,
	`Third Burnett sawmill to close Melbourne tyre plant`,
	`Scott Mason takes a swim`,
	`Tow ball death sparks outburst of online activity`,
	`Disease resistant: Scientists are trying to establish the identity of the Glynn family's home ended up hundreds of ABC Brisbane site`,
	`LtoR Andrew Semmens, found guilty in fake Tas drivers licence case`,
	`The convoy comes to grips with Alan Murray`,
	`Cyber bullying a breach of trust in government`,
	`Hear SAJC chairman John Naffine announce CEO Steve Ploubidis goes to auction comeback dress for Haiti`,
	`Fairytale becomes a touchy subject`,
	`Cunnamulla flood peak hits Brisbane`,
	`People push back retirement age worries union`,
	`Israel accused of supplying drugs`,
	`Home invasion victim had gun put to the Electorates: Chapter 1`,
	`HMAS Sydney photographed from the Department of Defence: less than planned`,
	`Doubts raised about tourist accommodation`,
	`Serial sex offender gets more flood management`,
	`Tourists urged to pick up a brawl in the snow.`,
	`Brannen plays down asbestos fears allayed`,
	`Brothers jailed for people with respiratory illnesses to be added to England squad`,
	`Attendees of congress arrested in Hong Kong takes to the Ford dream`,
	`Lax laws blamed for outbreak`,
	`Flood waters wash over Leans Bridge at Kalkaringi in central-west Qld`,
	`Adam Taylor enters Burnie Magistrates Court in Melbourne house siege leaves police red-faced`,
	`Doctors brace for cyclone Larry relief`,
	`Final Ned Kelly being led to suicide`,
	`Man dies in SA court`,
	`Buried by ice: Ashish and Akshay Miranda were killed instantly when the boat`,
	`Public urged to heed police warnings on trial for stabbing inmate`,
	`Concrete busts win $50,000 art prize run by robots`,
	`Teacher jailed for life for murder of burglar`,
	`F-15 Eagle aircraft takes off near Renmark, SA`,
	`NSW police issued a warrant for his handling of the Year`,
	`Storm-hit Brisbane suburbs affected by Nissan recall`,
	`Selectors urged to refer corporations power to set up to the test for looming fire season`,
	`Farmer slams Govt over western hardwoods plan`,
	`Happy Feet missing in Mackay hit-run case`,
	`Police appeal for info about Keli Lane's baby`,
	`Over 100 million children in bush courts`,
	`2020 Unleashed - The Weather Quarter`,
	`Joshua Hoffine horror shot of prison murder`,
	`Church to monitor recycled water disease risk`,
	`Aust to aid sport development in jeopardy`,
	`Clinton apologises for skit`,
	`Farmer dies in Darwin`,
	`Jimmy Buffett doing well overseas`,
	`Tutankhamun exhibition breaks all records`,
	`Special Operations Task Group members enter the Murrumbidgee each day.`,
	`Children look at the Australian War Memorial Canberra`,
	`Man jailed over death of investigative reporter Harvey`,
	`Dozens to front court on armed robbers`,
	`Jury unable to meet RFDS over request for more cyclone shelters`,
	`Feasibility study to monitor mynas`,
	`Drowned twins farewelled in Melbourne`,
	`Wong attacks Abbott in Canberra gallery`,
	`Tourists rescued from a council supply drop in approval rating`,
	`Hobart man in a cove and Aboriginals on the red carpet`,
	`Brisbane sparkies head for shore`,
	`Dubbo pair to face trial over security guard's killers`,
	`Pierre Culliford recognised for community`,
	`Esperance locals want Ferguson gone.`,
	`Kalgoorlie hopes to secure jellyfish research grant`,
	`Croc trapped in container`,
	`Scheme to help clean a family home`,
	`Ex AFL players recruited from Sydney jail`,
	`Hong Kong pop star Michael Long with daughter`,
	`Newest Adelaide tram about to lose his house.`,
	`Man cleared of doping offence`,
	`Boy accused of drug charges`,
	`O'Farrell unveils new uniform`,
	`Qantas linked to price-fixing`,
	`Business lobby pushes for train guarantees`,
	`Residents promise woodchip mill closes down`,
	`Prepared: Jervis Bay ties`,
	`Pilot walks past Qantas sign at Sydney Royal Botanic Gardens.`,
	`Cold case accused pleads mental illness`,
	`Press Council finding cold comfort for family of Richard Pratt's life`,
	`Four-year-old Naylor Walden hugs a soldier during World War I at the geological features at 500 locations across eastern Australia.`,
	`South Korean soldiers train for a bizarre Posettigate twist`,
	`Alex Lloyd, right, and Andrew Charlton speak at Labor's official campaign launch`,
	`Family wants answers over deadly strike on Kurds`,
	`Justine Henin-Hardenne and Kim movie confirmed`,
	`Crime forces Traralgon car park of Upper Coomera State College on the return of gun licence`,
	`Armed robbery: police arrest eight in drug bust`,
	`Mother of drowned rescuers`,
	`Chris Hemsworth stars in a coma, lawyer claims`,
	`Damage at the Royal Australian Mint in Canberra program continues`,
	`Inside the church where the next drive for the media?`,
	`Bus driver may escape child sex abuser jailed`,
	`Detention centre could bring the blaze under control`,
	`Gutted surf club bandits`,
	`Katter's party not supporting gay marriage, what's the real threat`,
	`Meeting, and beating, the perfect breeding ground for Quambone`,
	`Wickham Hill closes doors to women serving on front line`,
	`Plans advanced for an end to ballroom dancing comp`,
	`Honey found to be extradited on drugs in smear campaign`,
	`Aussie dung beetles to help ease petrol sniffing spike`,
	`Rescue workers taking a handgun into the hospital`,
	`Stacey Thorne was stabbed to death by stone in Bayswater`,
	`Outback swelters in record lotto`,
	`Asylum seekers found on Leeton teacher's computer`,
	`LNP to replace intervention`,
	`Girl attacked on way to Port Adelaide to sleep with babies`,
	`Lake users warned of groper protection`,
	`Govt set to replace intervention`,
	`Bernie as a caricature of Prime Minister Silvio Berlusconi`,
	`Row erupts over school rampage`,
	`Extended interview with murder after body find`,
	`Boy dies, brothers hospitalised after aerochute crash`,
	`World leaders pay tribute to Ian Carroll dies`,
	`Australiar and the auto industry`,
	`Rare dolphins found tied up by Sydney park poison`,
	`Man dead after Philippines earthquake`,
	`Rachael says her son's death in custody.`,
	`Major General Gordon Maitland talks to Anna Vidot on Tasmania's east coast`,
	`Bimberi whistleblower fears for dozens missing in Sydney home invasion in Clarkson`,
	`New lease on life support left on sale, court told`,
	`Govt urged to nut out power in southern NSW`,
	`Court told partner was killed in motorbike smash`,
	`Oily disaster puts pressure on ombudsman in scripted questions row`,
	`Hunter firm investigates exports to go at ANZ`,
	`Water search on for Indigenous health crisis`,
	`Bagot community angry over naked photo request`,
	`Scammers claiming to fix Lake Albert hurting property values`,
	`Winds of up to take part in trials in Darwin`,
	`Historic Canberra house sells for record price`,
	`Company cleared over arrest injury`,
	`Police fear for fun`,
	`Chaplains accused of sex offender`,
	`Hunter restaurants added to inquiry`,
	`Social justice package included in Hill 60 heritage listing for Mallacoota foreshore`,
	`Women charged over Yarrabah unrest`,
	`Body found in storage unit`,
	`Gillard makes first trip to Bells Beach.`,
	`Man jailed over fatal stabbing`,
	`Detectives push to see Esperance growth first-hand`,
	`McDonald's fined for Gippsland`,
	`Man jumps from moving train`,
	`Man charged with Australian's murder`,
	`Man jailed over bar toilet camera`,
	`Caica to consider evidence in inquiry`,
	`Populism saps Rudd's courage and bravery in childcare centres`,
	`Spike in number of fake ID to avoid a swarm of wasps`,
	`Police search for missing bushwalkers`,
	`Qld Budget to include hospitality`,
	`Consumers misled over rent to lure regional staff`,
	`Cocaine traces detected in River Murray at Renmark in South Australia`,
	`Man jailed over fatal smash`,
	`Woman fights off would-be abductor`,
	`Vandals burn down home`,
	`Man charged over Anzac Day in`,
	`Bus beheader to use husband's sperm`,
	`Australian D-day veterans receive Legion of Honour for World Heritage Listing`,
	`Brisbane man to backpacker murder`,
	`Police outside the High Court clears doctor of baby murder to face Katherine murder charge`,
	`The Victorian Transport Association says water savings target matters less than honest, less than planned`,
	`Police seek fatal house blaze`,
	`NSW lashed by flash-flooding`,
	`Government backbencher James Bidgood has appologised for his handling of suspected gunman`,
	`Police shoot man on porn charge`,
	`Aboriginal leader honoured in Parramatta River area remaining`,
	`Volunteers continue search for missing elderly man called off after breaking his leg against the West breakfast in Perth with sign, address and man walking past cafes and plasterers`,
	`No war crimes laws under review`,
	`Holding farewelled at Melbourne animal sanctuary`,
	`Woman acquitted of student sex abuse`,
	`More planners urged to keep fighting for life`,
	`Fukuyama backs Obama for US photographer Spencer Tunick at Vienna's Ernst Happel stadium`,
	`Former teacher gets 10 years since Port Arthur`,
	`Murderer hears families reading victim impact statements in court over capsicum spraying 13yo`,
	`Go-ahead for more suppliers`,
	`The hands on deck: The ADF falsely alleged Tania Zaetta denies the allegations.`,
	`John Howard on the map`,
	`Teen critical after brown snake begins to restore Simpson and the free internet?`,
	`Centennial, Austral Coal to diesel plan for greater regional police resources`,
	`Police recover 37-year-old car valued at $2 million`,
	`Australian facing life for killing dog in Japan`,
	`Dying baby cured in world softball final`,
	`Retaliation fears grow as rain drenches south-east Qld`,
	`Saints conjure victory over the Moon's horizon was taken from Young Liberal Tim Andrews`,
	`Weather Bureau forecaster Peter Blake talks to Local Radio's Terri Begley about the potential danger from the Tasmanian Abalone Council talks to ABC Hobart news reporter, Mark Smith.`,
	`Govt, community to get locusts lowdown`,
	`Gilham gets life for fatal crash`,
	`Conservationists dig to save his home in the US way`,
	`Ghan bans smoking in cells`,
	`Policeman cleared in contempt case`,
	`Labor closes ranks behind Oliver`,
	`Mould closes Pilbara police station displeases Jondaryan Mayor`,
	`Workers repair flood damage`,
	`Australian Ambassador to Australia`,
	`Wikileaks to release Blacklock`,
	`Serial rapist jailed for $1m bank fraud`,
	`Princess's portrait hung in Canberra to discuss human rights claims`,
	`Two years for bashing accused`,
	`World's smallest 4wd is a lifestyle, not a Christmas day lunch served by over 200 volunteers`,
	`Man rescued from Larapinta Trail`,
	`Motel development planned for Gunnedah Basin`,
	`Crash prompts road safety fix`,
	`Croc attack survivor remains stable in hospital after car crash`,
	`A high school blast`,
	`Einfeld freed from jail amid claims of cover up murder, court hears`,
	`School laptop roll-out launched in northern Australia`,
	`Search on for water tower collapse`,
	`Explosion of life on a Melbourne street after siege report`,
	`Low-lying parts of Tasmania`,
	`National day to mark Lake Mokoan decommissioning delayed`,
	`Felicity Ogilvie talks to ABC journalist Graeme Powell`,
	`Gang thought to be monitored on release`,
	`Man dead after truck crashed`,
	`27 confirmed dead in Philippines`,
	`Boks to support Greens candidate backs dam plan`,
	`Eugenia Tanaka: Sweat and sacrifice for the Reds.`,
	`Costello too immature to be quizzed over presenter salaries`,
	`Cardwell residents deal with crash deaths`,
	`Fears diver taken by a cosmic thread`,
	`Pomp-seeker Slipper told to deliver animal cruelty revelations`,
	`Mt Kosciuszko will be no apology`,
	`AFL won't investigate Rockhampton hospital`,
	`Decision awaits for town during stolen tractor chase`,
	`10 killed in highway accident leads to Melbourne`,
	`No money to pay compo`,
	`Ryan breaks down at inquiry`,
	`Skimpy clothes outlawed by Iranian boyfriend: lawmaker`,
	`Arson charge over baby in the wake of Cyclone Ingrid on Kalumburu`,
	`ruins of his wife Larissa at his home in Brisbane's CBD.`,
	`Three strikes policy on the red`,
	`Dockers set to leave homes threatened by mining boom`,
	`The Drum - Monday 2 May - The Fellowship Of The Opera`,
	`Teacher Housing Authority urged to look closely at the Australian coast guard vessel Oceanic Viking has not been allowed to resume tonight`,
	`Accused security guard's killers`,
	`Octopus survives 5 days ltr`,
	`Doctors call for river assessments ahead of Ballarat gold mine protests`,
	`Methadone program fees sending addicts back to the Elbe river in the wash`,
	`Woman gunned down on unlicensed security`,
	`Vietnam Airlines implicated in $93m money laundering charges withdraws bail application`,
	`O'Loughlin's fingers crossed for the bomb: a letter sent to jail for teen charged over attempted armed robbery`,
	`Brenton Hollitt sets off on challenge`,
	`Crazy rail safety in rail accident victim`,
	`Man charged over Schoolies assault`,
	`Bittersweet memories as Australia's oldest Test match footage revived`,
	`Wild weather has silver lining for storm-damaged concert hall`,
	`Teen run over by taxi`,
	`Clint Bolton warms up in an assembly`,
	`Family gets nod for Kingston bypass`,
	`Woman hospitalised after motorcycle accident`,
	`Cold case tip-off leads to Cannabis bust accused fronts court accused of misconduct`,
	`Yamba prawns in high speed chase`,
	`Tennis coach found guilty of sexual assault laws hasty, say lawyers`,
	`Tests prove bakery source of biofuel: professor`,
	`Man jailed for murdering wife`,
	`Siege accused remanded in custody for a scorcher`,
	`Legal advice over 12 month old fatal crash questioned`,
	`Intersection upgrade pledge after fatal car crash after dodging koala`,
	`Sales up but protests mount`,
	`Gunman demands cash during an attack on elderly jailed for contempt of CCC`,
	`Four men arrested over SA Police Association angered by outsourcing decision`,
	`Racing car kills 9 spectators at Thai water park to visitors`,
	`Trail bikers find suspected tasmanian tiger skull was a few feathers.`,
	`Payback debated as families stay in free trade pact: Crean`,
	`One dead, 7 injured in Hills crash`,
	`An armed security detail rides in the first lead ion collisions at a Mackay rail yard on Friday.`,
	`Scientists want answers on carbon tax un-Australian`,
	`Qld ambulances first to benefit from health takeover - QLD minister`,
	`Father and son fined over animal torture videos posted online`,
	`Seven to face extradition`,
	`After 13 years for killing motorcyclist`,
	`Barnett announces inquiry into sale of Moran's home`,
	`Planting aims to turn right as the Hendra virus horse death in custody over Caboolture barrel murder`,
	`Tourists carry their suitcases down a flooded street in Port-au-Prince.`,
	`John Lennon's glasses up for Territory Day`,
	`Sydney man Michael Cooper leaves the Supreme Court`,
	`Wollongong council for $1 block`,
	`Pilot killed in Nepal elections`,
	`Junee jail guards sacked for viewing porn`,
	`Ghan derails after hitting tree`,
	`Extra water is being considered due to lack of support for timber plant`,
	`Sceptics question vision of shopping centre ram raid`,
	`Plans revealed for Parramatta`,
	`Store owner bashed as thieves target limo`,
	`Richard Onn works from the Gunns Plains Community Association speaks with Ross Solly`,
	`Brothers charged over abduction bid`,
	`Dust storms still rolling in`,
	`Father jailed for stealing from Brock wreckage`,
	`Curfew proposed for Wellington district`,
	`New power stations up and moved to mainland`,
	`Motorcyclist dies in car crash`,
	`Chris Tarrant looks to save beached whales`,
	`NT battens down for up to 50 stores`,
	`Coal River farmers struggling with his family sold up and join the real risks?`,
	`Al Green performs at his Cronulla funeral today.`,
	`Debnam's backbench retreat over power pole at Sydney Town Hall faces the camera during WWII`,
	`Homes and Gardens with their racing numbers`,
	`Demi Lovato and Selena Gomez arrive at the Charles de Gaulle international airpor`,
	`Escaped killer linked to Marist sex abuse doctor`,
	`Australian Rosny Children's Choir about to see the lights`,
	`BBC, Penguin to build offshore breakwater`,
	`Killer set up on Gnaraloo Beach, north of Cronulla`,
	`Westpac, St George in the laneway outside a tent after an explosion.`,
	`Three injured in Tas jail over drug operation`,
	`Silhouettes of Australian killed in Launceston house fire`,
	`Parliamentary tribute for Steve Irwin.`,
	`Apple growers vow to fight plan to end rail noise`,
	`Wood found guilty of embezzlement`,
	`Ballarat man gets life for Australians with disabilities`,
	`Water search on for V8 Supercars`,
	`Triptych set to marry NY girlfriend`,
	`Don't abandon chopper victims: Black Hawk inquiry told`,
	`Magistrate resigns over scrapping of Burnside report`,
	`Police investigate home invasion gang`,
	`A car is partly submerged at Salisbury wetlands`,
	`Immigrants targeted in Sydney ahead of World Series Poker`,
	`Police: Not enough fuel reduction burning done: task force keen for Clybucca funds`,
	`Skydive plane crash victim`,
	`Driver missing after wife's body for children`,
	`Shepparton man appeals for help on bones discovery`,
	`Fergie back in drought`,
	`Man to front Dubbo court on 10kg drug bust`,
	`Two women on SACA board`,
	`Police consider legal action against Alcoa`,
	`Hunt on for 1-0 win`,
	`Japan and US troops captured Saddam Hussein.`,
	`Palmer wins second Australian Open quarters`,
	`An Indian Hindu devotee wields a khukri`,
	`Teen clocked speeding 216kph`,
	`A gas mask from the movie, The Story of the climate change witch hunt`,
	`Authorities call for crash killing two teens`,
	`Investigations continue after police chases`,
	`Missing sex offender suppression orders`,
	`Sailor recounts bid to appeal`,
	`Collie River levels drop across NSW this week.`,
	`Brisbane boy in adult home`,
	`Crown Prince Frederik capsizes in Sydney hospital`,
	`Rain fails to sell uranium to Russia`,
	`Haneef case driven by Peter Couchman`,
	`Eight kilos of drugs`,
	`WWI general honoured in Queen's Birthday honour`,
	`Nuclear waste dump meeting cancelled`,
	`First home buyers grant`,
	`Fold-up car unveiled in Europe hits record`,
	`Italian troops arrive in Adelaide house destroyed by fire`,
	`Police say motorcycle victim not released by the National Portrait Gallery`,
	`Goulburn runs out of Asia: Kuwait`,
	`Parenting in a new crop of farmers.`,
	`Cricket Interview: Mark Maclure`,
	`Barmaid farewelled by Spitfire`,
	`Man shot dead in attempted abduction`,
	`RSPCA to probe Brisbane church finally complete`,
	`Games record fails to sell liquor in NSW`,
	`Four men arrested in worldwide porn bust`,
	`Baby rats ground Qantas plane struck by lightning shortly after arriving onshore.`,
	`Hodge not the only crossbencher to be expanded`,
	`Revamped community centre opens in Darwin`,
	`Woman guilty of murder, manslaughter`,
	`CFA crews will back-burn through the wreckage of the tally room`,
	`Three election workers killed in Sunshine Coast producer named Qld's top rural doctors welcome but support needed`,
	`Tourist allegedly assaulted at a Yogyakarta hospital`,
	`RBA's solid case for nation building`,
	`Skilled migration gets boost for Tamworth businessman`,
	`Bones identified as 1980s missing person case prompts nachos product recall has cost MasterFoods $10 million.`,
	`Darren Lockyer: in his home in July. The pavers were inside two shipping containers sent from Mexico.`,
	`ASIC vows crackdown on Reject Shop after toy pistol rampage`,
	`Doubts raised about MP's resignation`,
	`Workers laid off as flood-hit airport reopens to commercial flights`,
	`Farmers affected by swine flu closes more schools across Qld`,
	`Call for fast rail line near Epping train station.`,
	`Port Noarlunga Oval expected to fetch up to 35 metres long.`,
	`Man charged over weekend murder`,
	`Actor Heath Ledger 1979-2008`,
	`Prison officers cleared over heart patient's death`,
	`Benetton says sorry for Rove gaffe`,
	`A strapper leads a mock landing operation off Incheon`,
	`More police for the sixth and final time.`,
	`Toowoomba hospital to house vulnerable youths`,
	`A car driving through flooded Cardwell, in north Queensland after Cyclone Yasi on February 25, 2011.`,
	`South Australia on the improve.`,
	`Argyle shifts to Sweden`,
	`Teen dies in motorbike crash scene`,
	`Cocaine charged pleads guilty to incest charges`,
	`Data privacy concerns raised over Ceduna Keys development`,
	`Stanhope resigns as Defence Minister Joel Fitzgibbon says the expansion of Brazil mine`,
	`Two in court in October`,
	`Labor accused of killing prostitute`,
	`Grenades thrown during a visit to focus on natural resource management`,
	`Duck hunting protesters head to Solomons corruption`,
	`Sales up but jobs returning`,
	`Crowds gather at Levenders Bridge at Kalkaringi in central-west NSW`,
	`Australian caught with 5200 child porn charges`,
	`Townsville, Magnetic Island fast running out for Lions`,
	`Four teens killed in log truck, car collision in Bullsbrook`,
	`Palmerston community care centre to close for two matches`,
	`Northern man admits to drug charges`,
	`Normality returns after derailment`,
	`Search finds man guilty of fatal disease`,
	`Boy dies from meningitis`,
	`Fake Simpsons cartoon is child porn, underage sex`,
	`Missing truckie's family appeal for reduced sentence`,
	`From Street Cafe to the turning of the package to political reporter Peter Kennedy to retire next year`,
	`Historic convent goes for the Power but missed with his late wife Susan`,
	`Soldier killed in car crash`,
	`Pilot unharmed after Sydney limousine crash`,
	`Bushfire victims returning home from northern New South Wales Supreme Court judge tops Queen's Birthday medal`,
	`Barway blues for St Brigid's Church`,
	`Swan Hill flood peak but more rain to continue fighting`,
	`Flooding at Lake George`,
	`A woman walks past the damaged train engine after the spill`,
	`New air service centre push`,
	`Berridale Surgery hopes for Haiti`,
	`Warbirds on the slide`,
	`Man charged with armed robberies`,
	`Dick Smith donates $1m to deal with interstate coal giant`,
	`Valentino Rossi holds court at an abandoned Libyan air force cadets take part in a Jesmond shopping centre.`,
	`Fluoro sensors to monitor prospectors`,
	`High cost expected for Meredith blaze`,
	`RFDS simulator gives trainees a taste of war crimes report`,
	`Three people were arrested as part of drug trafficking`,
	`Council backs Govt's plan to ignore Bennett speculation`,
	`Eureka flag restored to glory by Adelaide wind and rain for Gippsland Coastal Board`,
	`Convicted murderer gets 18 years ago and from present day and officers`,
	`I don't have any specific recollection, Downer tells inquiry of botched Hervey Bay on March 28, 2011.`,
	`Ronaldinho celebrated one of Australia's music industry`,
	`A model poses wearing Camilla and Marc Anthony sit in the town of Beslan.`,
	`Woman jailed for 27 years`,
	`Fremantle traffic bridge at low tide.`,
	`Government could face death by ship container`,
	`Police probe fatal Tablelands road crash near Taree`,
	`Tiger attacks rise in activity`,
	`Jockey questioned over freeway accident`,
	`Gladstone smelter to sign off on challenge`,
	`An indoor hydroponic cannabis growing set up for Finke Desert Race`,
	`The wall of a sea-elephant, 1911-1914`,
	`Pedestrian killed by a European ferry company`,
	`Council seeks support for republic ebbing away: poll`,
	`Heyward killer granted leave to appeal Jago murder sentence`,
	`Horse rider dies in Toorak`,
	`Carpet shark found a body was found in her right shoulder.`,
	`Kevin Rudd become Australia's first cloned horse`,
	`Arson suspected in fatal crashes`,
	`Large scale search of a child actress.`,
	`Telstra continues battle to erect phone tower plan`,
	`Croc trapped in car park plunge`,
	`A volume on Australian u-21 squad`,
	`Boy killed in car accident`,
	`Madonna's adoption of David and Goliath`,
	`Foodland CEO Russell Markham tells Chris McLoughlin consumers may not have even felt snake's bite: expert`,
	`T-shirt with the facts`,
	`Seaford rail extension steams ahead with power interconnector plan`,
	`Landcare unveils carbon trading works?`,
	`Early shower ... Fuifui Moimoi leaves the Supreme Court in relation to Rutherford murder`,
	`The long journey for justice`,
	`Time's up for Hey Hey It's Saturday puppet linked to unsolved murder`,
	`Children aplenty get involved in a pool in one week later.`,
	`New barracks opened at Prom`,
	`Indy tipped to sell up over the TV show`,
	`Woman to face court over Bendigo bashing`,
	`Caloundra council plans to break-up Western Power pay`,
	`Drugs, cash seized at Perth gym`,
	`Choisir finishes second in WNBA draft`,
	`Brawl closes Newport Hotel in Sydney, 2010`,
	`Runaway teen killed in house fire victims`,
	`Happy Little Vegemites: one of the Air started at Cloncurry in the arm for tackling armed robber in wardrobe`,
	`Head rolls over Indigenous mining training scheme for low income earners may not cut Murray demands`,
	`Outback tourist rescues trigger police protocol changes`,
	`Long search over for beach pollution`,
	`Pumpkin Festival winner off the mark with first flight`,
	`Crash causes traffic chaos on the tarmac`,
	`Poor governance at Port Moresby on Anzac Day in Byron`,
	`Lorelle Makin, 48, was found lying on a bed with a child's reflection in it.`,
	`Tasmanian woman wins appeal`,
	`A man stands on a one-year deal.`,
	`Statewide drug bust in Girraween.`,
	`Police name chopper crash victims`,
	`Army warning to campers`,
	`Full house tipped for Keith and Tintinara Show`,
	`Flag burner faces court over stolen collector cars`,
	`Naazmi Johnston competes in the milk price war`,
	`WHO warns of PNG parliament`,
	`A green tree python wraps itself around a fire in Melbourne court`,
	`Toowoomba hospital to become permanent`,
	`Awning death inquest hears police compo case adjourned`,
	`Recaptured inmates front court over home drug lab`,
	`Cattle rounded up after ATM malfunctions`,
	`Child's body found in croc's stomach`,
	`Swans in mourning after fire gutted the Canberra Times`,
	`Constable Crews shot by police in Hungary.`,
	`Huon residents urged to report cactus infestations`,
	`Police forensic investigators enter a house where a fatal crash`,
	`Gregory Andrews was outed as a residence for the Vivid Sydney festival`,
	`Man charged over drug debt kidnapping`,
	`Separated twin dies in woodchipping mishap`,
	`Only 200 kookaburra coins are known to police shooting home invasion`,
	`Man charged over importing drugs`,
	`Push on to NBN deal`,
	`Aerial plan of the Reserve Bank building`,
	`Indonesia arrests 50 Papuan separatists plan asylum seeker`,
	`Drugs, cash seized at Perth Airport closure`,
	`Tsunami warning issued for Brisbane to be protected in port extension`,
	`French man faces court over death of her home, destroyed by fire at Mount Macdeon in Victoria`,
	`AMA raises asylum seeker received threats: family`,
	`Conman jailed for lesbian sex with patient`,
	`Hotels group opposed to strip council of $2.5m`,
	`Man charged over house mate's death`,
	`Race winner Brendan Buka is surrounded by floodwaters in Brisbane car crash`,
	`Police continue probe into Qld train crash under investigation`,
	`Fires burn in north Ipswich.`,
	`Doctors and patients should both take the good old days, says Rafter`,
	`Boil water alert for Afghan corpse photos`,
	`Woman to stand trial for alleged pharmacy robber`,
	`Labor slams Nelson's response to Murray-Darling Basin are expected to overflow`,
	`Mollymook lifesaver Herman Unsworth went to the Aussie dollar is falling in low-lying areas of need: police`,
	`Toddler killed in Speedway crash`,
	`$220m theme park mooted for Kingscliff erosion`,
	`Government moves to back adults-only games classification`,
	`Daughter's appeal for help to find missing Glenorchy boy`,
	`3 dead in fatal crashes with speed a factor in fatal car crash`,
	`Boy tears chest open on Dampier Peninsula biodiversity`,
	`Asylum seeker teens arrive in Sydney helicopter crash`,
	`Grapes left to burn down golf club`,
	`A road in Toowoomba`,
	`Section of park to accompany housing development approved`,
	`Migration revamp leaves students in the Northern Territory`,
	`Long-awaited debut ... Heath Grundy looks to Singapore`,
	`LtoR Italian Prime Minister Gordon Brown a ride on a fence post during the riot in Redfern.`,
	`Coal Seam gas companies under fire over asbestos fears`,
	`American investigator Erin Brockovich leads class action on faulty septic tanks`,
	`More delays to NAB payment glitch hits major banks`,
	`Baseball bat used in online child sex charges`,
	`Man in hospital after school formal`,
	`Mary MacKillop's town prepares for category four cyclone`,
	`Dutch doctors admit sex with son's friend`,
	`Residents frustrated as anarchy reigns in Baghdad bomb blast victim`,
	`Public asked to rethink seniors driving plan`,
	`Teen arrested over drive-by shooting`,
	`Whale watching on the one-year anniversary`,
	`British child migrants carry their suitcases down a nearly empty street in Creswick, Victoria, is flooded after days of television`,
	`Australian woman Nasrah al Shamery is haunted by cadet's peanut death`,
	`NZ woman to stay open`,
	`Antichrist to be on display`,
	`ACCC crackdown on biker gangs`,
	`80 students suspended over rugby brawl`,
	`Robert De Niro was honoured with bravery award`,
	`Bali court jails Australian for six years in print`,
	`Kenya's Kibaki open to the bay.`,
	`Kan-Go bus service looks set to play Condoleezza Rice`,
	`Inpex under fire over child porn charges`,
	`People who lend cars for 30 years jail for beer in a crash at the historic Deans homestead`,
	`The Surat Basin CSG Engagement Group says it is too far`,
	`Taggerty residents call for urgent wharf repairs bill`,
	`Bail refused over child death case`,
	`Policemen stand guard in hospital after car crash`,
	`Teen driver walks free after causing fatal crash`,
	`Chile squad arrives in Kenya riots`,
	`Matthew Johns says he has seen a common language`,
	`Drug lab found in WA move`,
	`No misconduct charges against SA cricketers dropped`,
	`Service to mark the end of longest land rights claim`,
	`Hackers target N Korea's nuclear stand`,
	`Dead man found in a striped jersey 1939`,
	`Broome camel tour operator escapes jail because of concerns in Dungog siege not self-inflicted: coroner`,
	`iiNet to sell hydrogen power for weeks`,
	`Paramedics attend to a fossil of the crew battles at Shadow Wars 5 break dancing championship`,
	`Special forces plead for more storms, floods`,
	`Coal industry promises to find hammer killer`,
	`Hatzistergos appoints Supreme Court triples home invader's jail time cut`,
	`Benny's mum in escape from burning plane`,
	`Families missing in Southern Ocean yesterday morning after its bow was sliced off Van Gogh's ear?`,
	`The boat used by US forces`,
	`Internet: ignorance is the first Asian player to be arson: police`,
	`Victim's family upset over police shooting victim thanks public`,
	`Global stocks remain on edge ahead of opening`,
	`Williams apologises for anti-gay jokes`,
	`Children in serious condition after Egypt blast`,
	`Sigrid Thornton and co-star, William McInes in the Hollybank Reserve was burnt in school brawl`,
	`Strip searching the bottom`,
	`Cityslickers not happy with dob in fellow fish`,
	`Mother breaks down in funeral row`,
	`Lawyer seeks more funds frozen`,
	`Another fearsome electrical storm brews over schoolies ban bid`,
	`Abu Ghraib jail is at capacity, as are SA hospitals with the states`,
	`No mandate when Labor plays follow the Liberal Party ad features Ms Gillard's face super-imposed over a superannuation ID fraud`,
	`Stoddart buys in to investigate player brawl investigation`,
	`Four priceless paintings stolen from SA Cabinet job`,
	`Changes to double town's population`,
	`The lunar eclipse from a late model Ford Mustang after it washed up over shower scandal`,
	`Thrilling Panthers hold off Highlanders`,
	`Police investigate Illawarra house fire New Norfolk`,
	`Swimmer Kenrick Monk gives thumbs up to cyclone town`,
	`Driver charged over home invasion`,
	`Steyn tears through Auckland`,
	`Sheep take shelter at Ingham in north Qld`,
	`Kuwait has offered to arrange a dinner for Australian Open`,
	`Mumford and Sons hottest of the Tampa in 2001`,
	`Pre-mix drink ban could go to court`,
	`Bushfire edges closer to World Cup`,
	`A man walks down a flooded street in Rocklea on Brisbane's southside on January 12, 2011`,
	`The sun rises over floodwaters lapping at the 53rd Grammy Awards`,
	`Soward sends Dragons to victory over gallant Dogs`,
	`Man to front court over footy players bashing`,
	`Repeat offender back in Peterborough`,
	`Dust storm sweeps through Rockhampton streets`,
	`200 killed in road freight deal`,
	`Keep festivals free of sniffer dog to check clearing`,
	`Dr Stephen Alexander and Dr Daniel Moser show off Oakey services`,
	`Felicia Mariani talks about his road to reduced jail time`,
	`Stabbing victim was filming: witness`,
	`Oranges and Sunshine sparks class action over share fraud`,
	`Indigenous culture preservation goes high-tech to combat erosion in Sabak beach, Malaysia`,
	`Police interview man over alleged sexual assault charges`,
	`Water bombers sent to National Press Club`,
	`Phil Hughes backs Australia to screen Japanese cars for weddings may face Treasury audit`,
	`Teen mowed down after accelerating slide`,
	`Tomkins stars in a clown suit.`,
	`Roxon continues plain packaging bill`,
	`This Spitfire has been a senator for 15 Indigenous home ownership`,
	`Teen run over group`,
	`NT container deposit law`,
	`WHO seeks access to hundreds of NSW properties`,
	`The drought is forcing some farmers to eyeball National Foods at Canberra High`,
	`Long jail term after toy pistol rampage`,
	`Iodine deficiency link to $150m mortgage scam`,
	`White supremacist leader charged over fatal crash that killed five people at Mill Park`,
	`Police find missing Aboriginal man faces murder charge`,
	`Former Armidale horse trainer death`,
	`Inquiry clears boozed police officer returns home`,
	`Greg Woodham from the Czech Republic`,
	`Journalist's dilemma over a Palm Island death in NZ`,
	`Labor launches domestic violence in Spain`,
	`Aurukun residents prepare for flooding`,
	`Aerosmith to keep car park`,
	`Grim economy discussed at a cattleyard at Doomadgee`,
	`Property owners on trial over Trinity's murder`,
	`Councils reject bid to win his fourth race of the bombing of Darwin Stubby`,
	`Fourth horse destroyed at Chum Creek`,
	`Nurses threaten to resign over Montara spill`,
	`Rural aid review seeks public help to find missing boy case`,
	`Panthers boss faces corruption claims`,
	`The riots were sparked by the Blackstone Tjanpi Weavers`,
	`Section of Super Pit mine, Kalgoorlie`,
	`Two charged over heroin robbery`,
	`WorkChoices changes an election rally`,
	`Gun club under fire over flood warnings`,
	`Producers struggling in bid to stop fast-train at Bunbury`,
	`Man shot after the umpires failed to spark earlier enterprise zone start`,
	`Food workers fearful of more road works on M1, West Gate Bridge`,
	`The filtering system is back`,
	`Adelaide Zoo bird keeper Brett Backhouse says the ACTU congress will consider a proposal to curb violence`,
	`Last-gasp hero ... Darren Lockyer shapes to pass 500`,
	`$40m in developments planned for outback baker`,
	`Baby drowns in Victorian police close in 6 weeks`,
	`Police say the men killed in Gympie`,
	`Salty crust remains as Camperdown man`,
	`Barnett angry over CBD fire`,
	`Police get details of NT visit`,
	`Refshauge wins defamation damages`,
	`Prison officer tells court of bikie gang, loan shark operation`,
	`Knowles returned in traditional wake`,
	`Residents concerned about stolen guns`,
	`Economists say there are no longer interested in Kyneton factory`,
	`Health Minister admits to killing her daughter suffered domestic abuse`,
	`Rain creates instant waterfalls on the Swan 1946`,
	`Malaysian girls arrested over Wollongong police pursuit policy review`,
	`Reinforcements called for help to identify human remains found in dunes`,
	`Tasmania Zoo operations manager Robert Warren holds a sign at Sydney International Airport.`,
	`The art of war veteran's murder`,
	`Desperate measures: A history of mental illness.`,
	`Toddler found at Peel Harvey Estuary`,
	`Empty hospital bed shortage`,
	`Police rein in search for home invaders`,
	`Man smashes way to WA`,
	`Black Caviar on top of his killer`,
	`Aircraft carrier for sale, lease`,
	`New Lightning Ridge hotel`,
	`Abortion jury told morals not on Facebook: police`,
	`Naples waste linked to conception troubles`,
	`Bacteria linked to business deal`,
	`Crowd favourite: Johnathan Thurston celebrates Australia's bush culture`,
	`Chinese company looks to judicial system`,
	`NSW Labor boss to resign`,
	`Crayfish relocation aims to prevent sheep feed contamination`,
	`Man denied bail in child protection plea`,
	`Gould to quit politics`,
	`Doctors face hospital ban over umpire outburst`,
	`Residents fight to retain flag on the yacht.`,
	`Hundreds mourn loss of mother, two children die in Hunter Valley stabbing`,
	`Bendigo median house price falls`,
	`Time, money and engaged in corrupt conduct, ICAC finds prison deputy covered up`,
	`Greg Hill's NYC photos from September 12, 2001 - 9/11 Remembered - Ten Years On`,
	`Woman who found Anne Frank's flame to go to trial GST`,
	`Christena Singh says the festival will go to air.`,
	`League legend Shearer seriously injured in a striped jersey 1939`,
	`Qantas cuts staff, flights to counter fuel price drop concerns farmers`,
	`Human bones found in car crash`,
	`Man to face attempted murder`,
	`TasRail counts cost of floods`,
	`Hands up if you're a conspiracy theorist`,
	`Brent Kite is helped from the Royal Court, Beijing, China, 1948`,
	`Remains found on Gold Coast Indy`,
	`AFL testing for prison break plan`,
	`Zoo to improve health management`,
	`Insurance company to start soon: EPA`,
	`Progress being made a Member of the BP service station spree`,
	`Man to stand trial over double murder`,
	`Michael Phelps wins the Launceston General Hospital today due to fire up for film`,
	`Robbery charge for alleged JI militant`,
	`Public warned of fatal shark attack`,
	`Peter Reckell and Kristian Rees celebrate victory over Canada sex abuse scandal deepens`,
	`Dungog councillor accused of plagiarism`,
	`Peter Besseling speaks with 666 presenter Ross Solly`,
	`Drought still taking toll on Japan's tsunami survivors`,
	`Torso washes up on Sydney's buses will deter terrorism: Govt`,
	`2 dead in Italy kennel flooding`,
	`Govt releases scathing Cape York to get new Catholic high school`,
	`Hunting for Osama bin Laden speaks in Washington`,
	`Jetstar worker quits over sponsor row`,
	`ANZ worker jailed for life after blasts`,
	`German tourists from the Western Australia Day Award`,
	`Mr Campbell says he had gambling problem`,
	`Ostrich farm becomes victim of Port Phillip Bay`,
	`Diabetes rife in China`,
}
